[package]
name = "madrify"
version = "0.1.0"
description = "Madrify"
authors = []
license = ""
repository = ""
edition = "2021"
rust-version = "1.85"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "madrify_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.6", features = [] }

[dependencies]
serde_json = "*"
serde = { version = "*", features = ["derive"] }
log = "*"
tauri = { version = "*", features = [] }
tauri-plugin-dialog ="*"
tauri-plugin-os = "*"
tauri-plugin-store ="*"
tauri-plugin-log = "*"
tauri-plugin-opener = "*"
tauri-plugin-http = "*"
rusqlite = { version = "*", features = ["bundled"] }
reqwest = { version = "*", default-features = false, features = ["form", "json", "query", "rustls"] }
hmac = "*"
sha1 = "*"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
futures = "*"
url = "*"
md5 = "*"
rand = "*"

biquad = "*"
cpal = "*"
symphonia = { version = "*", default-features = false, features = ["aac", "flac", "isomp4", "mp3", "ogg", "pcm", "vorbis", "wav"] }
walkdir = "*"
lofty = "*"
base64 = "*"
roxmltree = "*"
regex = "*"
unicode-normalization = "*"

[target.'cfg(target_os = "android")'.dependencies]
jni = { version = "*", default-features = false }
rustls-platform-verifier = "*"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-autostart = "*"
tauri-plugin-single-instance = "*"
tauri-plugin-drpc = "*"
tauri-plugin-positioner = "*"
tauri-plugin-updater = "*"
tauri-plugin-process = "*"
rust_cast = { version = "*" }
if-addrs = "*"
rustls = { version = "*", features = ["ring"] }
